### ISSUE TITLE
[BUG] Stack trace with failed SecretsManager pull

### ISSUE THREAD

**Issue by dgraeber** [awslabs/aws-codeseeder#16]
**Describe the bug**
When deploying without a SecretsManager configured, there is a stack trace stating that an error occurred.  This is true, an error occurred, but the stack trace is confusing as the build process continues.  

**To Reproduce**
Deploy a module via `seedfarmer` with a module that does not use SecretsManager (is not logging into DockerHub).  See the stack trace

**Expected behavior**
When not using DockerHub or SecretsMananger, this stack trace should not indicate an error?

** Sample Log**

```
An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
Traceback (most recent call last):
  File "/var/scripts/retrieve_docker_creds.py", line 24, in get_secret
    get_secret_value_response = client.get_secret_value(SecretId=secret_name)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 745, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret.
```

**Comment by dgraeber** [comment]
This is confusing to end users.  Perhaps error handling around `images/code-build-image/retrieve_docker_creds.py` can correct it?
