### ISSUE TITLE
[BUG] DescribeLogStreams operation: The specified log group does not exist

### ISSUE THREAD

**Issue by kukushking** [awslabs/aws-codeseeder#269]
**Describe the bug**
Occasional race condition causes codeseeder to fail when looking up CodeBuild log group before one is created:

```
[2024-11-11 20:46:06,417 | ERROR | _module_commands.py:226 | Deploy-2-base-ray-ecr ] Error Response from CodeSeeder: Build status was not SUCCEEDED  - {'AWS_REGION': 'eu-west-2', 'AWS_ACCOUNT_ID': '<REDACTED>', 'AWS_PARTITION': 'aws', 'CODEBUILD_BUILD_ID': 'codeseeder-diw:d67bba6a-6453-406c-998f-b5e3e7485963'}
Traceback (most recent call last):
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/bin/seedfarmer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/__main__.py", line 296, in main
    cli()
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/__main__.py", line 151, in apply
    commands.apply(
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_deployment_commands.py", line 867, in apply
    deploy_deployment(
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_deployment_commands.py", line 722, in deploy_deployment
    _deploy_validated_deployment(
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_deployment_commands.py", line 354, in _deploy_validated_deployment
    deploy_response = list(workers.map(_exec_deploy, mdos))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_deployment_commands.py", line 342, in _exec_deploy
    return _execute_deploy(mdo)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_deployment_commands.py", line 230, in _execute_deploy
    return commands.deploy_module(mdo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_module_commands.py", line 186, in deploy_module
    resp_dict_str, dict_metadata = _execute_module_commands(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_module_commands.py", line 445, in _execute_module_commands
    raise ex
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/seedfarmer/commands/_module_commands.py", line 428, in _execute_module_commands
    _execute_module_commands(
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aws_codeseeder/codeseeder.py", line 394, in wrapper
    build_info = _remote.run(
                 ^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aws_codeseeder/_remote.py", line 120, in run
    build_info = _execute_codebuild(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aws_codeseeder/_remote.py", line 84, in _execute_codebuild
    return _wait_execution(
           ^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aws_codeseeder/_remote.py", line 49, in _wait_execution
    stream_name = cloudwatch.get_stream_name_by_prefix(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/aws_codeseeder/services/cloudwatch.py", line 56, in get_stream_name_by_prefix
    response: Dict[str, Union[str, List[Dict[str, Union[float, str]]]]] = client.describe_log_streams(
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<REDACTED>/.pyenv/versions/3.11.1/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
```

**Comment by dgraeber** [comment]
@kukushking status?
